### ISSUE TITLE
按照步骤来设置没效果？

### ISSUE THREAD

**Issue by INX0769** [smuyyh/EasyGuideView#1]
// 复杂的提示布局，建议通过此方法，较容易控制
            .addView(createTipsView(), 0, loc[1] + view.getHeight(),
                            new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                            ViewGroup.LayoutParams.WRAP_CONTENT))
这个是必设的吗？

**Comment by smuyyh** [comment]
不是。这个是往里面直接添加View，后面还有addMessage，setPositiveButton。都不是必要的  看自己需求

**Comment by INX0769** [comment]
EasyGuide guide = new EasyGuide.Builder(getActivity())
                .addHightArea(ll_right_text_menu, HShape.RECTANGLE)
                .addIndicator(R.drawable.n_arrow_up,loc[0],loc[0])
                .setPositiveButton("知道了",16)
                .dismissAnyWhere(true)
                .addMessage("新增提单快捷按钮",18)
                .build();
        guide.show();
是不是需要在application中初始化，以上是我的测试代码

**Comment by smuyyh** [comment]
不用。但是要在 View 绘制完成之后，因为里面涉及到View宽高获取。

**Comment by INX0769** [comment]
直接一点效果都没有，断点测试能走通guide.show之后的代码

**Comment by smuyyh** [comment]
demo 跑过么？

**Comment by smuyyh** [comment]
在 View 绘制完成之后调用才有效果。

**Comment by INX0769** [comment]
正准备跑demo

**Comment by INX0769** [comment]
..............跑你的demo都有问题，背景高宽都有问题....

**Comment by smuyyh** [comment]
我天。刚搞错了   1.1.0是可以的  1.1.1 多提交了  我还在测。稍等

**Comment by INX0769** [comment]
![Uploading Screenshot_2016-12-26-17-10-00-232_com.yuyh.easyg.png…]()
![Uploading Screenshot_2016-12-26-17-09-50-354_com.yuyh.easyg.png…]()

**Comment by INX0769** [comment]
我切回1.1.0发现背景直接是透明，看到白色的提示

**Comment by INX0769** [comment]
-=-好吧我发现指示器的坐标设错了，1.1.0是可用的，建议封装一下按钮的点击事件可以方便连环引导

**Comment by smuyyh** [comment]
好的

**Comment by INX0769** [comment]
还有个建议，就是可以参考一下dialog跟popupwindow，暴露一个isShow()的方法出去，对于实际使用是很有必要

**Comment by smuyyh** [comment]
有这个方法呀~

**Comment by INX0769** [comment]
-=-眼瞎了

**Comment by smuyyh** [comment]
按钮点击事件也加上了。1.2.1
